Repository rhtools/vminfo-parser, pull requests merged in 2024-10, with the labels that each got.

#62 ci: Update workflows towards release
  .github/workflows/conventional-commit-pr.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/python.yaml
  pyproject.toml
  tests/images/hashes.json
  tests/images/test_plotter.png
  tests/images/test_visualize_disk_space_horizontal.png
  tests/images/test_visualize_disk_space_vertical.png
  tests/images/test_visualize_os_distribution.png
  tests/images/test_visualize_supported_os_distribution.png
  tests/images/test_visualize_unsupported_os_distribution.png
  tests/test_visualizer.py
Labels: CI/CD

#66 ci(release): initial pass at release promotion
  .github/workflows/conventional-commit-pr.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
Labels: CI/CD

#68 chore: merge with main
  .github/workflows/conventional-commit-pr.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/release.yaml
  README.md
Labels: chore

#69 feat: Add ability to generate yaml of arguments
  tests/const.py
  tests/test_clioutput.py
  tests/test_config.py
  vminfo_parser/config.py
  vminfo_parser/vminfo_parser.py
Labels: feature

#70 ci(release): Update release workflow
  .github/dependabot.yml
  .github/psr-templates/.release_notes.md.j2
  .github/workflows/conventional-commit-pr.yaml
  .github/workflows/prerelease.yaml
  .github/workflows/python.yaml
  .github/workflows/release.yaml
  CONTRIBUTING.md
  LICENSE
  pyproject.toml
  tests/README.md
  vminfo_parser/__init__.py
  vminfo_parser/_version.py
Labels: CI/CD

#71 chore(release-notes): Fix Release Note Template
  .github/psr-templates/.release_notes.md.j2
Labels: chore

#72 chore(legacy): drop legacy code
  legacy/README.md
  legacy/tests/main_test.py
  legacy/tests/set_column_headings_test.py
  legacy/vm_csv_parser.py
Labels: chore

#74 feat: Convert CLI Output to Tabulate
  requirements.txt
  tests/const.py
  tests/test_clioutput.py
  vminfo_parser/analyzer.py
  vminfo_parser/clioutput.py
Labels: feature

#77 ci(Dependabot): update Dependabot PR titles
  .github/dependabot.yml
Labels: CI/CD

#78 ci(test): refactor testing in GitHub Actions
  .github/workflows/python.yaml
  pyproject.toml
  tests/conftest.py
  tests/e2e/__init__.py
  tests/e2e/conftest.py
  tests/e2e/test_main.py
  tests/images/hashes.json
  tests/requirements.txt
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/test_clioutput.py
  tests/unit/test_config.py
  tests/unit/test_const.py
  tests/unit/test_main.py
  tests/unit/test_visualizer.py
  tests/unit/test_vmdata.py
Labels: CI/CD

#79 refactor(main): split main function into separate functions by command
  pyproject.toml
  tests/const.py
  tests/unit/test_main.py
  vminfo_parser/__init__.py
  vminfo_parser/__main__.py
  vminfo_parser/analyzer.py
  vminfo_parser/config.py
  vminfo_parser/vminfo_parser.py
Labels: refactor

#80 chore(typing): cleanup typing
  tests/conftest.py
  tests/e2e/conftest.py
  tests/e2e/test_main.py
  tests/unit/conftest.py
  tests/unit/test_clioutput.py
  tests/unit/test_main.py
  tests/unit/test_vmdata.py
  vminfo_parser/__init__.py
  vminfo_parser/__main__.py
  vminfo_parser/analyzer.py
  vminfo_parser/clioutput.py
  vminfo_parser/config.py
  vminfo_parser/visualizer.py
  vminfo_parser/vmdata.py
Labels: chore

#75 refactor(main): refactor analyzer environment filtering, os counting, and disk space counting
  tests/const.py
  tests/unit/test_main.py
  tests/unit/test_visualizer.py
  vminfo_parser/__main__.py
  vminfo_parser/analyzer.py
  vminfo_parser/config.py
  vminfo_parser/visualizer.py
  vminfo_parser/vmdata.py
Labels: refactor
